---
title: "Stat 585 - Reading data from files"
author: "Heike Hofmann"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your turn - Solution

The file `ushcn-v2.5-stations.txt` contains information on all weather stations in the USHCN network. This file is also in fixed width format.
**Read the file into R and plot latitude versus longitude.**

```
	----------------------------------------
	Variable             Columns    Type
	----------------------------------------
	COUNTRY CODE             1-2    Character
	NETWORK CODE               3    Character
	ID PLACEHOLDERS ("00")   4-5    Character
	COOP ID                 6-11    Character
	LATITUDE               13-20    Real
	LONGITUDE              22-30    Real
	ELEVATION              33-37    Real
	STATE                  39-40    Character
	NAME                   42-71    Character
	COMPONENT 1 (COOP ID)  73-78    Character
	COMPONENT 2 (COOP ID)  80-85    Character
	COMPONENT 3 (COOP ID)  87-92    Character
	UTC OFFSET             94-95    Integer
	-----------------------------------------
```

## First look at the data

```{r}
stations<-readLines("https://raw.githubusercontent.com/Stat585-at-ISU/materials/master/data/ushcn-v2.5-stations.txt", n = 5)
stations
```

## 

```{r message=FALSE,  warning = FALSE}
library(tidyverse)
stations <- read_fwf("https://raw.githubusercontent.com/Stat585-at-ISU/materials/master/data/ushcn-v2.5-stations.txt",
  col_positions = fwf_positions(
    start=c(1,3,4,6,13,22,33,39,42,73,80,87,94), 
    end  =c(2,3,5,11,20,30,37,40,71,78,85,92,95)))
# check that the formats are correct
stations %>% glimpse()

```

## 

We need to get the names in, 
Elevation needs to be converted to double
```{r}
names(stations) <- c("Country code", "Network code", "ID", "Coop ID",
                     "Latitude", "Longitude", "Elevation", "State",
                     "Name", "Comp1", "Comp2", "Comp3", "UTC offset")
stations$Elevation[is.na(as.numeric(stations$Elevation))]
stations$Elevation <- as.numeric(stations$Elevation)
```

Which Iowa stations do we have?

```{r}
stations[stations$State == "IA",]$Name
```    

##

Now we plot:

```{r warning = FALSE, message = FALSE}
us <- map_data("state")
stations %>% ggplot(aes(x = Longitude, y = Latitude)) +
  geom_path(aes(x = long, y = lat, group = group), data = us) +
  geom_point()
```
