---
title: "Stat 585 - Crosstalk"
author: "Heike Hofmann"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
---
```{r setup, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Making widgets talk to each other

## What is `crosstalk`?

- `crosstalk` is an add-on R package to `htmlwidgets` produced by RStudio.
- extends htmlwidgets and allows implementing cross-widget interactions: linked brushing and filtering. <br><br><br><br><br><br>
- Tutorial: http://rstudio.github.io/crosstalk/

## crosstalk Example

[Result](03_crosstalk-example-01.html)

```{r, eval = FALSE, fig.width=5, fig.height=4}
library(crosstalk)
library(shiny)
library(d3scatter)

shared_mtcars <- SharedData$new(mtcars)
bscols(widths = c(3,NA,NA),
  list(
    filter_checkbox("cyl", "Cylinders", shared_mtcars, 
                    ~cyl, inline = TRUE),
    filter_slider("hp", "Horsepower", shared_mtcars, 
                  ~hp, width = "100%"),
    filter_select("auto", "Automatic", shared_mtcars, 
                  ~ifelse(am == 0, "Yes", "No"))
  ),
  d3scatter(shared_mtcars, ~wt, ~mpg, ~factor(cyl), 
            width="300", height=250),
  d3scatter(shared_mtcars, ~hp, ~qsec, ~factor(cyl), 
            width="300", height=250)
)
```

## Another - crazy(!) - example

[Result](03_crosstalk-example-02.html)

```{r, eval = FALSE, warning = FALSE, fig.width=5, fig.height=4}
library(gapminder)
library(crosstalk)
library(ggplot2)
library(plotly)

g <- crosstalk::SharedData$new(gapminder, ~continent)

gg <- ggplot(g, aes(gdpPercap, lifeExp, color = continent, 
                    frame = year)) +
  geom_point(aes(size = pop, ids = country)) +
  geom_smooth(se = FALSE, method = "lm") +
  scale_x_log10()

ggplotly(gg) %>% 
  highlight("plotly_hover")
```


